### ISSUE TITLE
Ensure invoking Config Server endpoints is complete in Developer section

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#119]
See: http://docs.pivotal.io/spring-cloud-services/1-5/service-broker-and-instances.html#invoke-config-server-endpoints

This should not be in the `Service Broker and Instances` page and instead make sure it is covered in Config Server developer section.

**Comment by fifthposition** [comment]
This section is mostly up-to-date, but it's duplicate. This information is already covered in our "Service Instance Access" page in the developer guide: http://docs.pivotal.io/spring-cloud-services/1-5/common/service-instance-access.html#get-access-token-for-direct-requests-to-a-service-instance.

I'll remove this section from the operator guide (where it is now) and ensure that that developer page explains enough about this procedure.

**Comment by fifthposition** [comment]
This is up at:

* http://docs-scs.cfapps.io/spring-cloud-services/2-0/service-broker-and-instances.html ("Invoke Config Server Configuration Endpoints" section removed)
* http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/service-instance-access.html#get-access-token-for-direct-requests-to-a-service-instance (end of section updated with clearer info on accessing Config Server endpoints to get configuration values)

@csterwa FYI, the "Get Access Token for Direct Requests to a Service Instance" section is a partial, and it _is_ also in the "The Service Broker and Instances" page, but it's general (rather than the old dedicated section on Config Server configuration endpoints). I think that at least for now, this info might be OK to have in both operator and developer docs.
