### ISSUE TITLE
Add use of UAA generated client for errand credentials to Security Overview

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/docs-spring-cloud-services#146]
See implementation story: https://github.com/pivotal-cf/spring-cloud-service-broker/issues/362

The focus of our docs update might be a section that describes how SCS uses PAS UAA client now instead of UAA generated credentials as of SCS 2.0.

From @scottfrederick :

"under this section, there’s a `Users` `p-spring-cloud-services` section. with that story, that user goes away and we’ll use the `p-spring-cloud-services` OAuth token to talk to CC instead of that user.
http://docs-scs.cfapps.io/spring-cloud-services/2-0/common/security-overview.html#spring-cloud-broker-worker
there might be changes to the `Authorities` listed for that OAuth2 client based on that story also. if you write a docs story then Gareth or someone else working on the story can get you the details"

**Comment by fifthposition** [comment]
@spikymonkey Could you elaborate on this as Scott mentioned? :)

**Comment by spikymonkey** [comment]
Hey @fifthposition I think this is done now, in the updated version of the doc (https://docs.google.com/document/d/11vXWZOuW4cvqsJIjxqx5K9kuHj-hUCCHut5696m15W8/edit#), and @scottfrederick has sanity checked for us. But Chris mentioned that development take ownership of this doc since it's so tied to the code changes... That makes sense, I think, but I'm wondering how best to manage it. We could make PRs and ask you to review? Wdyt?

**Comment by fifthposition** [comment]
@spikymonkey That works for me.
