### ISSUE TITLE
Document mirror service refresh

### ISSUE THREAD

**Issue by alek-sys** [pivotal-cf/docs-spring-cloud-services#305]
There is a special key to force mirror-service to pull all the upstream git repos, `update-git-repos`. So operator can run this command:
```
$ cf update-service config -c '{ "update-git-repos": true }' 
```
To refresh mirrored repos for this SI. 

It feels to me that this should be documented, maybe even in a dediceted Mirror Service section so people know we are not using upstream git repos directly. WDYT @fifthposition @csterwa ?

**Comment by fifthposition** [comment]
@csterwa I think we ought to have at least a general Config Server section, if not a page, on the mirror service--I wouldn't have, because it's an implementation detail, but it _will_ come up in our docs so I think we should introduce it somewhere. We only hardly do (on the Config Server home page) right now. What do you think?

**Comment by csterwa** [comment]
Agreed. I think a general section that is high level is sufficient.

**Comment by fifthposition** [comment]
Added a page to "Operator Guide": http://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/common/config-server/mirror-service.html

**Comment by csterwa** [comment]
Looks great!
