### ISSUE TITLE
Add known issue for 2.0.x and 3.0.x: deletion complications because of shared org for backing apps

### ISSUE THREAD

**Issue by fifthposition** [pivotal-cf/docs-spring-cloud-services#334]
2.0.x and 3.0.x both use the `p-spring-cloud-services` org and each tile will attempt to delete it in its Broker Deregistrar pre-delete errand. This can cause problems if an operator is running 2.0.x and 3.0.x side-by-side and then deletes one of them.

* 2.x known issue: Do NOT uninstall SCS 2.x or prior versions if you have SCS 3.x installed. ISSUE: If you delete 2.x tile, it will delete all of the backing application spaces for 3.x instances and will cause outage for apps bound to those 3.x instances.
* 3.x We should post a similar message, but noted for the 3.x operator perspective (Don't uninstall 2.x yet)

**Comment by csterwa** [comment]
@fifthposition It looks like running the tile install errands did not recreate the `p-spring-cloud-services` org as I thought I'd verified. We will need to figure out a fix for this. I'm not sure what the resolution is for this since there is a need to not only create the org but also to provide permissions for broker to manipulate the org. So, if they do this I'm not sure how to fix it.

**Comment by fifthposition** [comment]
These are up now:

* [2.0.x Release Notes](https://docs-pcf-staging.cfapps.io/spring-cloud-services/2-0/release-notes.html)
* [3.0.x Release Notes](https://docs-pcf-staging.cfapps.io/spring-cloud-services/3-0/release-notes.html)
