### ISSUE TITLE
How can we use the config server with Runtime CredHub

### ISSUE THREAD

**Issue by nic0d** [pivotal-cf/docs-spring-cloud-services#94]
Hi,
I configured the PAS and Config server to use the last version with Runtime Credhub (http://docs.pivotal.io/pivotalcf/2-0/opsguide/secure-si-creds.html).
Everything is deployed, I successfully created and bound the service to my app, but I do not know how to use it. Is there any working example the shows how to consume Config Server with the Runtime Credhub configured ?

I wonder where, from a developer point of view I should find the url of Credhub. When I read the documentation on Config Server (without Credhub), there is the URL of the config server, but with Credhub, there is no URL.

Extract from the doc of config server (without Credhub)
```
"p-config-server": [
   {
    "credentials": {
     "access_token_uri": "https://p-spring-cloud-services.uaa.cf.wise.com/oauth/token",
     "client_id": "p-config-server-c4a56a3d-9507-4c2f-9cd1-f858dbf9e11c",
     "client_secret": "9aGx9K5Vx0cM",
     "uri": "https://config-51711835-4626-4823-b5a1-e5d91012f3f2.wise.com"
    },
    "label": "p-config-server",
    "name": "config-server",
    "plan": "standard",
    "tags": [
     "configuration",
     "spring-cloud"
    ]
   }
```

What I get from cf env APP
```
"p-config-server": [
   {
    "credentials": {
     "credhub-ref": "/c/p-spring-cloud-services/p-config-server/xxxx/credentials-json"
    },
    "label": "p-config-server",
    "name": "config-server-xxx",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "configuration",
     "spring-cloud"
    ],
    "volume_mounts": []
   }
```

According to this documentation, we are supposed to get the URL of the config server : http://docs.pivotal.io/spring-cloud-services/1-5/common/config-server/connectors.html

but I do not find any information on this point

Could you help me with a sample or more detailed explanation.

Thank you in advance

**Comment by fifthposition** [comment]
Hi @nic0d!

The documentation does not cover this because the Spring Cloud Services for PCF Config Server currently does not support CredHub as a backend. The supported backends are [Git](http://docs.pivotal.io/spring-cloud-services/config-server/configuring-with-git.html) and [HashiCorp Vault](http://docs.pivotal.io/spring-cloud-services/config-server/configuring-with-vault.html).

To give feedback or ask questions about the Spring Cloud Services for PCF product, if you are a Pivotal customer you can open a ticket with Pivotal Support or use the #scs-support-channel Slack channel. You can also add an issue to the open-source Spring Cloud Config repository. For this particular question, there is already an OSS Spring Cloud Config issue open: spring-cloud/spring-cloud-config#882.

Thanks for your interest and please do open an issue here if you find any problem with or have any question about the documentation! 😃

**Comment by scottfrederick** [comment]
@nic0d When you view the app's `VCAP_SERVICES` env var you will only see the `credhub-ref` key in the `credentials` block. However, Cloud Foundry will replace the `credhub-ref` with the raw credentials when the application is started in a container. The application doesn't have to do anything to get the config server URL. If your application uses Spring Boot actuators, you can verify this by hitting the `/env` endpoint and inspecting the `vcap` section in the response. 

If you want more details on how this works, you can watch this video from the last SpringOne: https://www.youtube.com/watch?v=gQnM_PIMuE8&t=17m30s
